name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: |
        docker build -t juandavidherrera/graphql-actions:1.0.2 .
        docker build -t juandavidherrera/graphql-actions .

    - name: Push Docker Image
      run: |
        docker push juandavidherrera/graphql-actions:1.0.2
        docker push juandavidherrera/graphql-actions
      
      
    
    # - name: Build the Docker image
    # docker build -t juandavidherrera/graphql-actions:1.0.0 .
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
